gradh/articles/urls.py
from django.urls import path
from . import views


app_name='articles'

urlpatterns = [
    path(''        , views.list   , name='list'),
    path('<int:article_id>/', views.single, name='single'),
    path('<int:article_id>/leave_comment', views.leave_comment , name = 'leave_comment'),
]

gradh/gradh/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path , include
from django.contrib.auth.views import LoginView, LogoutView
from . import forms
from datetime import datetime

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('main.urls')),
    path('articles/',include('articles.urls')),
    path('login/',
         LoginView.as_view
         (
             template_name='main/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Вхід',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gradh/main/urls.py
from django.urls import path
from . import views
from datetime import datetime
from django.conf.urls import url
from django.views.generic.base import RedirectView
from articles.models import Article
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap

info_articles = {
        'queryset': Article.objects.all(),
        'date_field': 'post_date',
    }

urlpatterns = [
    path('sitemap.xml', sitemap,
            {'sitemaps': {'aricles': GenericSitemap(info_articles, priority=0.6) , }},
            name='django.contrib.sitemaps.views.sitemap'),
    path(''        , views.index   , name='home'),
    path('about/'  , views.about   , name='about'),
    path('contact/', views.contact , name='contact'),
    path('register/', views.RegisterFormView.as_view( extra_context=
             {
                 'title': 'Реєстрація',
                 'year' : datetime.now().year,
             }) , name="register"),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/media/favicon.ico'), name='favicon'),
]

gradh/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    title = models.TextField("Назва" , max_length=200)
    article_text = models.TextField("Текст статті")
    keywords = models.CharField('Ключові слова' , max_length=120 , null = False , default = "keywords")
    imagin1 = models.ImageField("Картинка 1",upload_to='articles/' , blank=False, null=False)
    imagin2 = models.ImageField("Картинка 2",upload_to='articles/' , blank=True)
    imagin3 = models.ImageField("Картинка 3",upload_to='articles/' , blank=True)
    post_date = models.DateField("Дата публікації" , auto_now=False, auto_now_add=True)
    updated = models.DateTimeField("Редаговано" , auto_now=True, auto_now_add=False)
    author = models.ForeignKey(User , on_delete = models.CASCADE )
    link1 = models.URLField("Кнопка 1", blank=True)
    link1_name = models.TextField("Назва кнопки 1", blank=True)
    link2 = models.URLField("Кнопка 2", blank=True)
    link2_name = models.TextField("Назва кнопки 2", blank=True)
    link3 = models.URLField("Кнопка 3", blank=True)
    link3_name = models.TextField("Назва кнопки 3", blank=True)

    def __unicode__(self):
        return self.title
 
    def __str__(self):
        return self.title
 
    def get_absolute_url(self):
        return "/%s/" %(self.id)
 
    class Meta:
        ordering = ["-id", "-post_date"]
        verbose_name = "Стаття"
        verbose_name_plural = 'Статті'

class Comment(models.Model):
    article = models.ForeignKey(Article , on_delete = models.CASCADE)
    date_post = models.DateTimeField("Дата створення" , auto_now=False, auto_now_add=True)
    author = models.CharField('Імя коментатора',  max_length = 50)
    comment_text = models.CharField('Текст коментаря', max_length = 200)

    def __str__(self):
        return self.author

    class Meta:
        verbose_name = "Коментарій"
        verbose_name_plural = 'Коментарі'

gradh/articles/views.py
from django.http import Http404 , HttpResponseRedirect , HttpResponse
from django.shortcuts import render
from django.urls import reverse
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import get_object_or_404
from datetime import datetime
from django.shortcuts import render
from django.http import HttpRequest
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Article , Comment

def list(request):
    posts = Article.objects.all().order_by('-post_date')
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    querysetGoods = paginator.get_page(page)
    context = {
        "posts": paginator.get_page(page),
        'title':"Статті",
        'year':datetime.now().year,
    }
    return render(request, "articles/list.html", context)



def single(request, article_id):
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("Статтю не знайдено")

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render(request , "articles/detail.html" , {"article": a, 'latest_comments_list': latest_comments_list,'title':a.title, 'year':datetime.now().year,'author':a.author ,})

def leave_comment(request , article_id ):
    if request.user.username == "":
        ima = "Невідомий"
    else:
        ima = request.user.username
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("Статтю не знайдено")
    a.comment_set.create(author = ima, comment_text = request.POST['text'])

    return HttpResponseRedirect(reverse('articles:single' , args = (a.id,)))

gradh/articles/templates/articles/detail.html
{% extends "main/index.html" %}

{% load static %}



{% block title %}{% endblock %}

{% block content %}
<style>

        img {
            max-width: 100%;
            height: auto;
            width: auto\9; /* ie8 */
        }

        textarea {
            max-width: 100%;
            height: auto;
            width: auto\9; /* ie8 */
        }

        input[type="text"] {
            border: 1px solid gray;
            max-width: 100%;
            height: auto;
            width: auto\9; /* ie8 */
        }

        textarea[type="text"] {
            border: 1px solid gray;
            width: 100%;
            height: auto;
            width: auto\9; /* ie8 */
        }
    p {
        max-width: 100%;
            height: auto;
            width: auto\9; /* ie8 */
            word-wrap:break-word;
            
    }
    h1 {
        text-align: center;
        margin-bottom: 1em;
    }
</style>
<div class="container body-content">
<div class="jumbotron">
    <h1>{{article.title}}</h1>
    <div>
        <div class="row">
            <div class="col-md-12">
        {%if article.imagin1 %}
            <img src="{{MEDIA_URL}}{{ article.imagin1.url }}">
        {%endif%}
        <p></p>
            </div>
            <div class="col-md-6">
        {%if article.imagin2 %}
            <img src="{{MEDIA_URL}}{{ article.imagin2.url }}">
        {%endif%}
        <p></p>
            </div>
        <div class="col-md-6">
        {%if article.imagin3 %}
            <img src="{{MEDIA_URL}}{{ article.imagin3.url }}">
        {%endif%}
        <p></p>
            </div>  
        </div>
    </div>
    <p></p>
    <p>{{article.article_text}}</p>

    <em>Остання зміна {{article.updated}}</em>
    <br>
    <em>Автор - {{article.author}}</em>
    <p></p>
    <div class="row">
        <div class="col-md-4">
    {%if article.link1%}
    <a href={{article.link1}} class="btn btn-outline-success btn-block">{{article.link1_name}} &raquo;</a>
    {%endif%}
    <p></p>
        </div>
        <div class="col-md-4">
    {%if article.link2%}
    <a href={{article.link2}} class="btn btn-outline-success btn-block">{{article.link2_name}} &raquo;</a>
    {%endif%}
    <p></p>
        </div>
        <div class="col-md-4">
    {%if article.link3%}
    <a href={{article.link3}} class="btn btn-outline-success btn-block">{{article.link3_name}} &raquo;</a>
    {%endif%}
    <p></p>
        </div>
    </div>
</div>
<div class="jumbotron">
    {% if latest_comments_list %}
        {% for a in latest_comments_list %}
            <p>
                <strong>{{a.author}}</strong>
                <p>{{a.comment_text}}</p>
            </p>
        {% endfor %}
    {% else %}
    Коментарів немає , стань першим :)
    {% endif %}
    </div>
    <div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
    <form action="{% url 'articles:leave_comment' article.id %}" method="POST">
        {% csrf_token %}
        <h2>{{user.username}}</h2>
        <textarea name="text" required="" placeholder="Текст коментария" cols="50" rows="5"></textarea><br>
        <button type="submit" class="btn btn-primary btn-block">Оставить коментарий</button>
    </form>
    </div>
    </div>
    </div>
</div>
{% endblock %}

gradh/articles/templates/articles/list.html
{% extends 'main/base.html' %}

{% block content %}
<style>
  img {
      max-width: 100%;
      height: auto;
      width: auto\9; /* ie8 */
  }
</style>
<div class="container body-content">
<h1 style="text-align: center;">Статті</h1>
<br>
  {% load bootstrap4 %}
  {% bootstrap_pagination posts pages_to_show=5 %}
  {% if not posts %}
<b>Нічого немає</b>
  {% else %}
    {% for obj in posts %}
    <div class="jumbotron">
    <a href="{{ obj.id }}"><h3>{{ obj.title }}</h3></a>
      <div class="row">
          <div class="col-md-4">
              <img src="{{ obj.imagin1.url }}">
          </div>
          <div class="col-md-8">
            <p>{{ obj.article_text|truncatechars:200 }}</p>
          </div>
      </div>
      <span>{{ obj.post_date }}</span>
    </div>
<br>
    {% endfor %}
  {% endif %}

  {% bootstrap_pagination posts pages_to_show=5 %}
{% endblock %}
</div>